"""PDF document exporter."""

from __future__ import annotations

from io import BytesIO
from pathlib import Path
from typing import TYPE_CHECKING, ClassVar

from paperbanana.core.types import ExportConfig
from paperbanana.exporters.base import BaseExporter

if TYPE_CHECKING:
    from PIL import Image


class PDFExporter(BaseExporter):
    """Exporter for PDF format.

    For matplotlib-generated plots: Native PDF export (if source is available)
    For raster diagrams: Embeds image in PDF using reportlab

    Requires: reportlab>=4.0 (optional dependency)
    """

    format_name: ClassVar[str] = "PDF Document"
    file_extension: ClassVar[str] = ".pdf"

    async def export(
        self, image: Image.Image, output_path: Path, config: ExportConfig | None = None
    ) -> Path:
        """Export image as PDF.

        Args:
            image: PIL Image object to export
            output_path: Path where the PDF should be saved
            config: Optional configuration for export behavior

        Returns:
            Path to the exported PDF file

        Raises:
            ValueError: If export fails
            ImportError: If reportlab is not installed
        """
        if config is None:
            config = ExportConfig()

        # Ensure output path has correct extension
        if output_path.suffix.lower() != ".pdf":
            output_path = output_path.with_suffix(".pdf")

        # Create output directory if needed
        output_path.parent.mkdir(parents=True, exist_ok=True)

        try:
            from reportlab.lib.utils import ImageReader
            from reportlab.pdfgen import canvas
        except ImportError as e:
            raise ImportError(
                "PDF export requires reportlab. Install with: pip install paperbanana[export-pdf]"
            ) from e

        try:
            # Get image dimensions
            width, height = image.size

            # Convert DPI to points (72 points per inch)
            dpi_scale = 72.0 / config.dpi
            width_pt = width * dpi_scale
            height_pt = height * dpi_scale

            # Create PDF canvas
            c = canvas.Canvas(str(output_path), pagesize=(width_pt, height_pt))

            # Convert PIL Image to BytesIO for reportlab
            img_buffer = BytesIO()
            image.save(img_buffer, format="PNG")
            img_buffer.seek(0)

            # Draw image on canvas
            img_reader = ImageReader(img_buffer)
            c.drawImage(img_reader, 0, 0, width=width_pt, height=height_pt)

            # Add metadata if configured
            if config.embed_metadata:
                c.setTitle("PaperBanana Generated Diagram")
                c.setSubject("Academic diagram generated by PaperBanana")
                c.setCreator("PaperBanana")

            # Save PDF
            c.save()

        except Exception as e:
            raise ValueError(f"Failed to export PDF: {e}") from e

        return output_path

    def is_available(self) -> bool:
        """Check if reportlab is installed."""
        try:
            import reportlab  # noqa: F401

            return True
        except ImportError:
            return False

    def get_install_hint(self) -> str:
        """Get installation instructions for reportlab."""
        return "Install with: pip install paperbanana[export-pdf]"
